---
title: "320FinalProject"
authors: "Charles Bangert, Noah Tanenholtz, Ryan Dietz"
date: "5/9/2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Project for CMSC320: Introduction to Data Science

# Summary
In lieu of a final exam, CMSC320 students will turn in a tutorial that will walk users through the entire data science pipeline: data curation, parsing, and management; exploratory data analysis; hypothesis testing and machine learning to provide analysis; and then the curation of a message or messages covering insights learned during the tutorial. Students may choose an application area and dataset(s) that are of interest to them; please feel free to be creative about this!

Remember, the course resources page has a number of data repositories from where you can download data. You could also create your own dataset using scraping skills you have learned in class. We in fact, encourage this.

The tutorial should be self-contained as an Rmarkdown document, and delivered as a GitHub statically-hosted Page (described below). You can see examples here: https://www.kaggle.com/kernels?sortBy=votes&group=everyone&pageSize=20&language=R

In general, the tutorial should contain at least 1500 words of prose and 150 lines of (nonpadded, legitimate) R code, along with appropriate documentation, visualization, and links to any external information that might help the reader.